

import React from 'react';
import { Page, Lead, User, Deal, Todo, Campaign, TimelineEntry, Activity, Developer, Project, Unit, Owner, Channel, Stage, Status, Service, ServicePackage, ServiceProvider, Product, ProductCategory, Supplier } from './types';
import { ChartIcon, CheckSquareIcon, ChevronsUpDownIcon, FileTextIcon, HandshakeIcon, MegaphoneIcon, SettingsIcon, ShoppingBagIcon, StarIcon, TargetIcon, UsersIcon } from './components/index';

export const SIDEBAR_ITEMS: { 
  name: Page; 
  icon: React.FC<React.SVGProps<SVGSVGElement>>; 
  subItems?: Page[] 
}[] = [
  { name: 'Dashboard', icon: ChartIcon },
  { name: 'Leads', icon: TargetIcon, subItems: ['All Leads', 'Fresh Leads', 'Cold Leads', 'My Leads', 'Rotated Leads'] },
  { name: 'Activities', icon: StarIcon },
  { name: 'Inventory', icon: ShoppingBagIcon, subItems: ['Properties', 'Owners'] },
  { name: 'Deals', icon: HandshakeIcon },
  { name: 'Users', icon: UsersIcon },
  { name: 'Marketing', icon: MegaphoneIcon, subItems: ['Campaigns'] },
  { name: 'Todos', icon: CheckSquareIcon },
  { name: 'Reports', icon: FileTextIcon, subItems: ['Teams Report', 'Employees Report', 'Marketing Report'] },
  { name: 'Integrations', icon: ChevronsUpDownIcon, subItems: ['Meta', 'TikTok', 'WhatsApp'] },
];

export const SETTINGS_ITEM = { name: 'Settings', icon: SettingsIcon };

export const MOCK_USERS: User[] = [
  { id: 1, name: 'Admin', role: 'Owner', phone: '+1234567890', avatar: 'https://picsum.photos/id/1005/200/200', email: 'admin@example.com', username: 'admin', password: 'admin123', company: { id: 1, name: 'Real Estate Co.', specialization: 'real_estate' } },
  { id: 2, name: 'John Doe', role: 'Sales Agent', phone: '+1987654321', avatar: 'https://picsum.photos/id/1011/200/200', email: 'john.doe@example.com', username: 'johndoe', password: 'password123', company: { id: 1, name: 'Real Estate Co.', specialization: 'real_estate' } },
  { id: 3, name: 'Jane Smith', role: 'Sales Manager', phone: '+1122334455', avatar: 'https://picsum.photos/id/1012/200/200', email: 'jane.smith@example.com', username: 'janesmith', password: 'password123', company: { id: 2, name: 'Services Co.', specialization: 'services' } },
  { id: 4, name: 'Mike Johnson', role: 'Sales Agent', phone: '+1555666777', avatar: 'https://picsum.photos/id/1013/200/200', email: 'mike.johnson@example.com', username: 'mikejohnson', password: 'password123', company: { id: 3, name: 'Products Co.', specialization: 'products' } },
];

export const MOCK_TIMELINE: TimelineEntry[] = [
    { id: 1, user: 'Admin', avatar: 'https://picsum.photos/id/1005/200/200', action: 'Lead Created', details: 'Lead was created from Facebook Ad channel.', date: '2024-10-21 09:15' },
    { id: 2, user: 'John Doe', avatar: 'https://picsum.photos/id/1011/200/200', action: 'Call Logged', details: 'No answer on first call attempt.', date: '2024-10-21 14:30' },
    { id: 3, user: 'Admin', avatar: 'https://picsum.photos/id/1005/200/200', action: 'Data Modified', details: 'Updated budget from 700000 to 750000.', date: '2024-10-22 11:00' },
];

export const MOCK_LEADS: Lead[] = [
  { id: 1, name: 'Ahmed Amiri', phone: '+96612345678', lastFeedback: 'Initial contact made', notes: 'Interested in property X', lastStage: 'FOLLOWING', reminder: '2024-10-25 10:00', status: 'Touched', type: 'Fresh', assignedTo: 1, budget: 500000, authority: 'Decision Maker', communicationWay: 'Call', priority: 'High', channel: 'Facebook Ad', createdAt: '2024-10-20 10:00', history: MOCK_TIMELINE.slice(0,1) },
  { id: 2, name: 'Test 2', phone: '+96687654321', lastFeedback: 'No answer on first call', notes: '', lastStage: 'NO ANSWER', reminder: '2024-10-22 14:00', status: 'Untouched', type: 'Fresh', assignedTo: 2, budget: 750000, authority: 'Influencer', communicationWay: 'Call', priority: 'Medium', channel: 'Website', createdAt: '2024-10-21 09:15', history: MOCK_TIMELINE },
];

export const MOCK_DEALS: Deal[] = [
    { id: 1, clientName: 'Ahmed Amiri', unit: 'Villa #12', paymentMethod: 'Cash', status: 'Reservation', value: 500000, project: 'Downtown Dubai', startDate: '2024-10-20', closedDate: '2024-11-20', startedBy: 2, closedBy: 3 },
    { id: 2, clientName: 'Test 2', unit: 'Apt 301', paymentMethod: 'Installment', status: 'Contracted', value: 750000, project: 'Palm Jumeirah', startDate: '2024-09-15', closedDate: '2024-12-15', startedBy: 2, closedBy: 2 },
    // FIX: Changed 'name' to 'clientName' to conform to the Deal interface.
    { id: 3, clientName: 'New Client', unit: 'Penthouse A', paymentMethod: 'Cash', status: 'Closed', value: 1200000, project: 'Downtown Dubai', startDate: '2024-10-01', closedDate: '2024-10-10', startedBy: 3, closedBy: 3 },
];

export const MOCK_ACTIVITIES: Activity[] = [
    { id: 1, user: 'John Doe', lead: 'Ahmed Amiri', type: 'Call', date: '2024-10-21 14:30', notes: 'No answer on first call attempt.' },
    { id: 2, user: 'Admin', lead: 'Test 2', type: 'Note', date: '2024-10-22 11:00', notes: 'Updated budget from 700000 to 750000.' },
    { id: 3, user: 'Jane Smith', lead: 'Ahmed Amiri', type: 'Meeting', date: '2024-10-23 10:00', notes: 'Scheduled a meeting for next week.' },
    { id: 4, user: 'John Doe', lead: 'Test 2', type: 'Whatsapp', date: '2024-10-24 09:00', notes: 'Sent brochure via WhatsApp.' },
];

const getFutureDate = (days: number) => {
    const date = new Date();
    date.setDate(date.getDate() + days);
    return date.toISOString().split('T')[0];
};

export const MOCK_TODOS: Todo[] = [
    { id: 1, type: 'Hold Reminder', leadName: 'Ahmed Amiri', leadPhone: '+96612345678', dueDate: getFutureDate(2) }, // In 2 days
    { id: 2, type: 'Call', leadName: 'Test 2', leadPhone: '+96687654321', dueDate: getFutureDate(0) }, // Today
    { id: 3, type: 'Meeting', leadName: 'New Client', leadPhone: '+96655555555', dueDate: getFutureDate(1) }, // Tomorrow
    { id: 4, type: 'Call', leadName: 'Sarah Johnson', leadPhone: '+1-555-0104', dueDate: getFutureDate(1) }, // Tomorrow
    { id: 5, type: 'Meeting', leadName: 'Michael Brown', leadPhone: '+1-555-0105', dueDate: getFutureDate(3) }, // In 3 days
    { id: 6, type: 'Call', leadName: 'Fatima Al-Zahrani', leadPhone: '+966559876543', dueDate: getFutureDate(0) }, // Today
];

export const MOCK_CAMPAIGNS: Campaign[] = [
    { id: 1, name: 'Riyadh Summer Promo', code: 'RYS24', budget: 15000, createdAt: '2024-09-01', isActive: true },
    { id: 2, name: 'Jeddah Waterfront Launch', code: 'JWL24', budget: 25000, createdAt: '2024-08-15', isActive: false },
];

export const MOCK_DEVELOPERS: Developer[] = [
    { id: 1, code: 'DEV001', logo: 'https://picsum.photos/seed/dev1/40/40', name: 'Emaar Properties' },
    { id: 2, code: 'DEV002', logo: 'https://picsum.photos/seed/dev2/40/40', name: 'Nakheel Properties' },
];

export const MOCK_PROJECTS: Project[] = [
    { id: 1, code: 'PROJ001', name: 'Downtown Dubai', developer: 'Emaar Properties', type: 'Residential', city: 'Dubai', paymentMethod: 'Installments' },
    { id: 2, code: 'PROJ002', name: 'Palm Jumeirah', developer: 'Nakheel Properties', type: 'Mixed-use', city: 'Dubai', paymentMethod: 'Cash' },
];

export const MOCK_UNITS: Unit[] = [
    // Empty for now to show "No units found" message
];

export const MOCK_OWNERS: Owner[] = [
    { id: 1, code: 'OWN001', city: 'Riyadh', district: 'Al Malaz', name: 'Abdullah Al-Fahd', phone: '+966501234567' },
    { id: 2, code: 'OWN002', city: 'Jeddah', district: 'Al-Hamra', name: 'Fatima Al-Zahrani', phone: '+966559876543' },
    { id: 3, code: 'OWN003', city: 'Dammam', district: 'Al-Shati', name: 'Mohammed bin Saleh', phone: '+966533219876' },
];

// Services Mock Data
export const MOCK_SERVICES: Service[] = [
    { id: 1, code: 'SVC001', name: 'Consultation Service', description: 'Professional consultation', price: 500, duration: '1 hour', category: 'Consulting', isActive: true },
    { id: 2, code: 'SVC002', name: 'Maintenance Service', description: 'Regular maintenance', price: 300, duration: '2 hours', category: 'Maintenance', isActive: true },
    { id: 3, code: 'SVC003', name: 'Installation Service', description: 'Product installation', price: 800, duration: '3 hours', category: 'Installation', isActive: true },
];

export const MOCK_SERVICE_PACKAGES: ServicePackage[] = [
    { id: 1, code: 'PKG001', name: 'Premium Package', description: 'Complete service package', price: 2000, services: [1, 2], duration: '1 day', isActive: true },
    { id: 2, code: 'PKG002', name: 'Basic Package', description: 'Basic service package', price: 1000, services: [2], duration: '4 hours', isActive: true },
];

export const MOCK_SERVICE_PROVIDERS: ServiceProvider[] = [
    { id: 1, code: 'PRV001', name: 'Tech Solutions', logo: 'https://picsum.photos/seed/provider1/40/40', phone: '+966501111111', email: 'info@techsolutions.com', specialization: 'IT Services', rating: 4.5 },
    { id: 2, code: 'PRV002', name: 'Maintenance Pro', logo: 'https://picsum.photos/seed/provider2/40/40', phone: '+966502222222', email: 'info@maintenancepro.com', specialization: 'Maintenance', rating: 4.8 },
];

// Products Mock Data
export const MOCK_PRODUCTS: Product[] = [
    { id: 1, code: 'PRD001', name: 'Product A', description: 'High quality product', price: 1500, cost: 1000, stock: 50, category: 'Electronics', sku: 'SKU-001', isActive: true },
    { id: 2, code: 'PRD002', name: 'Product B', description: 'Premium product', price: 2500, cost: 1800, stock: 30, category: 'Electronics', sku: 'SKU-002', isActive: true },
    { id: 3, code: 'PRD003', name: 'Product C', description: 'Standard product', price: 800, cost: 500, stock: 100, category: 'Accessories', sku: 'SKU-003', isActive: true },
];

export const MOCK_PRODUCT_CATEGORIES: ProductCategory[] = [
    { id: 1, code: 'CAT001', name: 'Electronics', description: 'Electronic products' },
    { id: 2, code: 'CAT002', name: 'Accessories', description: 'Product accessories' },
    { id: 3, code: 'CAT003', name: 'Software', description: 'Software products' },
];

export const MOCK_SUPPLIERS: Supplier[] = [
    { id: 1, code: 'SUP001', name: 'Global Supplies', logo: 'https://picsum.photos/seed/supplier1/40/40', phone: '+966503333333', email: 'info@globalsupplies.com', address: 'Riyadh, Saudi Arabia', contactPerson: 'Ahmed Ali', specialization: 'Electronics' },
    { id: 2, code: 'SUP002', name: 'Tech Distributors', logo: 'https://picsum.photos/seed/supplier2/40/40', phone: '+966504444444', email: 'info@techdist.com', address: 'Jeddah, Saudi Arabia', contactPerson: 'Sarah Mohammed', specialization: 'IT Equipment' },
];

export const MOCK_TEAMS = [
  { id: 1, name: 'Sales Team A' },
  { id: 2, name: 'Sales Team B' },
];

export const MOCK_EMPLOYEE_REPORT_DATA = [
    {
        id: 1,
        name: 'admin',
        totalLeads: 100,
        calledLeads: 80,
        notCalledLeads: 20,
        untouchedLeads: 15,
        touchedLeads: 85,
        following: 50,
        meeting: 10,
        doneMeeting: 5,
        followAfterMeeting: 3,
        rescheduleMeeting: 2,
        cancellation: 5,
        noAnswer: 10,
        outOfService: 2,
        notInterested: 8,
        whatsappPending: 5,
        hold: 2,
        broker: 1,
        resale: 0,
        closedDeal: 4,
        totalCalls: 150,
        answeredCalls: 120,
        notAnsweredCalls: 30,
        delayedReminderLeads: 3,
        totalDeals: 7,
        reservationDeals: 2,
        inProgressDeals: 1,
        closedDeals: 4,
        cancelDeals: 1,
    }
];

export const MOCK_CONNECTED_ACCOUNTS = {
    facebook: [
        { id: 1, name: 'My Real Estate Page', status: 'Connected', link: 'https://facebook.com/realestate' },
        { id: 2, name: 'Luxury Villas Dubai', status: 'Connected', link: 'https://facebook.com/villasdubai' },
    ],
    tiktok: [],
    whatsapp: [],
};

// Settings Mock Data
export const MOCK_CHANNELS: Channel[] = [
    { id: 1, name: 'Website', type: 'Web', priority: 'High' },
    { id: 2, name: 'Facebook', type: 'Social', priority: 'Medium' },
    { id: 3, name: 'Google Ads', type: 'advertising', priority: 'High' },
    { id: 4, name: 'Newsletter', type: 'email', priority: 'Medium' },
];

export const MOCK_STAGES: Stage[] = [
    { id: 1, name: 'New Lead', description: 'Just arrived, untouched.', color: '#3b82f6', required: true, autoAdvance: false },
    { id: 2, name: 'Qualified', description: 'Contacted and budget confirmed.', color: '#10b981', required: true, autoAdvance: true },
    { id: 3, name: 'Proposal', description: 'Sent the official proposal.', color: '#8b5cf6', required: false, autoAdvance: false },
];

export const MOCK_STATUSES: Status[] = [
    { id: 1, name: 'Active', description: 'Lead is currently active.', category: 'Active', color: '#22c55e', isDefault: true },
    { id: 2, name: 'Follow Up', description: 'Requires a follow-up call.', category: 'Follow Up', color: '#3b82f6' },
    { id: 3, name: 'No Answer', description: 'Could not reach the lead.', category: 'Inactive', color: '#f59e0b' },
    { id: 4, name: 'Not Interested', description: 'Lead is not interested.', category: 'Closed', color: '#ef4444', isHidden: true },
];


export const translations = {
    en: {
        hello: "Hello LOOP CRM! 👋",
        welcomeBack: "Welcome Back!",
        signInToContinue: "Sign in to continue managing your customer relationships efficiently.",
        crmWelcome: "The future of customer relationship management.",
        crmDescription: "Automate repetitive tasks, enhance productivity, and improve your workflows with our intuitive CRM.",
        username: "Username",
        password: "Password",
        signIn: "Sign In",
        pleaseEnterCredentials: "Please enter username and password",
        invalidCredentials: "Invalid username or password",
        search: "Search",
        searchEllipsis: "Search...",
        all: "All",
        user: "User",
        // Sidebar
        dashboard: "Dashboard",
        leads: "Leads",
        allLeads: "All Leads",
        freshLeads: "Fresh Leads",
        coldLeads: "Cold Leads",
        myLeads: "My Leads",
        rotatedLeads: "Rotated Leads",
        activities: "Activities",
        inventory: "Inventory",
        properties: "Properties",
        owners: "Owners",
        deals: "Deals",
        users: "Users",
        marketing: "Marketing",
        campaigns: "Campaigns",
        // FIX: Added missing translation key.
        campaign: "Campaign",
        todos: "Todos",
        reports: "Reports",
        teamsReport: "Teams Report",
        employeesReport: "Employees Report",
        marketingReport: "Marketing Report",
        integrations: "Integrations",
        meta: "Meta",
        facebook: "Facebook", // Keep for backward compatibility with data
        tikTok: "TikTok",
        whatsApp: "WhatsApp",
        // FIX: Added missing translation key.
        website: "Website",
        settings: "Settings",
        channels: "Channels",
        stages: "Stages",
        statuses: "Statuses",
        logout: "Logout",
        // Dashboard
        todayNewLeads: "Today New Leads",
        todayTouchedLeads: "Today Touched Leads",
        todayUntouchedLeads: "Today Untouched Leads",
        delayedLeads: "Delayed Leads",
        weekLeadsReport: "Week Leads Report",
        stagesReport: "Stages Report",
        topUsers: "Top Users",
        latestFeedbacks: "Latest Feedbacks",
        noDataAvailable: "No data available",
        // Leads
        filter: "Filter",
        addLead: "Add Lead",
        assignLead: "Assign Lead",
        name: "Name",
        phone: "Phone",
        actions: "Actions",
        lastFeedback: "Last Feedback",
        notes: "Notes",
        lastStage: "Last Stage",
        reminder: "Reminder",
        view: "View",
        add_action: "Add Action",
        // View Lead
        unassign: "Unassign",
        addDeal: "Add Deal",
        editClient: "Edit Client",
        details: "Details",
        communicationWay: "Communication Way",
        authority: "Authority",
        priority: "Priority",
        dates: "Dates",
        createdAt: "Created At",
        timeline: "Timeline",
        // Activities
        allUsers: "All users",
        today: "Today",
        yesterday: "Yesterday",
        last7Days: "Last 7 Days",
        thisMonth: "This Month",
        allLeadsType: "All Leads Type",
        freshLead: "Fresh Lead",
        coldLead: "Cold Lead",
        call: "Call",
        meeting: "Meeting",
        whatsapp: "Whatsapp",
        note: "Note",
        lead: "Lead",
        type: "Type",
        date: "Date",
        noActivitiesFound: "No activities found for the selected filters.",
        // Properties
        createNew: "Create New",
        addDeveloper: "Add Developer",
        addProject: "Add Project",
        addUnit: "Add Unit",
        // Services
        services: "Services",
        servicePackages: "Service Packages",
        serviceProviders: "Service Providers",
        duration: "Duration",
        rating: "Rating",
        // Products
        products: "Products",
        productCategories: "Product Categories",
        suppliers: "Suppliers",
        cost: "Cost",
        stock: "Stock",
        sku: "SKU",
        contactPerson: "Contact Person",
        specialization: "Specialization",
        realEstateOnly: "This page is only available for Real Estate companies.",
        servicesOnly: "This page is only available for Services companies.",
        productsOnly: "This page is only available for Products companies.",
        active: "Active",
        inactive: "Inactive",
        units: "Units",
        projects: "Projects",
        developers: "Developers",
        searchUnits: "Search Units",
        noUnitsFound: "No units found.",
        logo: "Logo",
        developer: "Developer",
        city: "City",
        paymentMethod: "Payment Method",
        update: "Update",
        delete: "Delete",
        bedrooms: "Bedrooms",
        // FIX: Added missing translation key.
        bathrooms: "Bathrooms",
        price: "Price",
        // Owners
        addOwner: "Add Owner",
        district: "District",
        // FIX: Added missing translation key.
        zone: "Zone",
        noOwnersFound: "No owners found.",
        // Deals
        searchDeals: "Search Deals",
        createDeal: "Create Deal",
        dealId: "ID",
        value: "Value",
        // Create Deal
        createNewDeal: "Create New Deal",
        dealInformation: "Deal Information",
        project: "Project",
        startedBy: "Started By",
        closedBy: "Closed By",
        startDate: "Start Date",
        closedDate: "Closed Date",
        discountPercentage: "Discount Percentage",
        discountAmount: "Discount Amount",
        totalValue: "Total Value",
        salesCommissionPercentage: "Sales Commission Percentage",
        salesCommissionAmount: "Sales Commission Amount",
        description: "Description",
        // Users
        autoAssignment: "Auto Assignment",
        on: "On",
        off: "Off",
        viewUser: "View User",
        createUser: "Create User",
        editUser: "Edit User",
        deleteUser: "Delete User",
        salesAssistant: "Sales Assistant",
        owner: "Owner",
        nameRequired: "Name is required",
        usernameRequired: "Username is required",
        emailRequired: "Email is required",
        passwordRequired: "Password is required",
        phoneRequired: "Phone is required",
        roleRequired: "Role is required",
        invalidEmail: "Invalid email format",
        passwordMinLength: "Password must be at least 6 characters",
        // Campaigns
        addCampaign: "Add Campaign",
        isActive: "Is Active",
        yes: "Yes",
        no: "No",
        noResultsFound: "No results found.",
        // Todos
        thisWeek: "This Week",
        noTasksForDate: "No tasks for",
        // Reports
        allTeams: "All Teams",
        selectFiltersPrompt: "Select filters to view the report.",
        totalCalls: "Total calls",
        answered: "Answered",
        notAnswered: "Not Answered",
        // Integrations
        integration: "Integration",
        addNewAccount: "Add New Account",
        disconnect: "Disconnect",
        noAccountsConnected: "No accounts connected",
        connectAccountPrompt: "Click 'Add New Account' to connect your page and start capturing leads.",
        // General
        status: "Status",
        code: "Code",
        budget: "Budget",
        role: "Role",
        email: "Email",
        unit: "Unit",
        // Settings
        leadAssignmentSettings: "Lead Assignment Settings",
        autoRotation: "Enable Auto Rotation for Delayed Leads",
        autoRotationDesc: "When enabled, the system automatically reassigns leads that have not been attended to within a specified time.",
        reminderDelayTime: "Reminder Delay Time (Minutes)",
        reminderDelayTimeDesc: "This time determines how long to wait before a lead is marked as 'delayed'.",
        saveSettings: "Save Settings",
        channelAutomation: "Channel Automation",
        multiChannelTracking: "Enable Multi-Channel Lead Tracking",
        defaultChannel: "Default Channel",
        defaultChannelDesc: "Assign a channel to any new leads with an unknown source.",
        activeChannels: "Active Channels",
        addChannel: "Add Channel",
        channel: "Channel",
        addType: "Add Type",
        typeName: "Type Name",
        enterTypeName: "Enter type name",
        stageAutomation: "Stage Automation",
        autoStageAdvancement: "Enable Auto Stage Advancement",
        requireStageCompletion: "Require Stage Completion",
        leadStages: "Lead Stages",
        addStage: "Add Stage",
        stageName: "Stage Name",
        required: "Required",
        autoAdvance: "Auto Advance",
        statusConfiguration: "Status Configuration",
        enableCustomStatuses: "Enable Custom Statuses",
        requireStatusUpdates: "Require Status Updates",
        defaultActiveStatus: "Default Active Status",
        defaultActiveStatusDesc: "Set the default status for all new leads.",
        availableStatuses: "Available Statuses",
        addStatus: "Add Status",
        category: "Category",
        followUp: "Follow Up",
        closed: "Closed",
        // Modals & Drawers general
        submit: "Submit",
        cancel: "Cancel",
        reset: "Reset",
        applyFilters: "Apply Filters",
        edit: "Edit",
        confirmDelete: "Are you sure you want to delete this item? This action cannot be undone.",
        // AddLeadModal
        addNewLead: "Add New Lead",
        clientName: "Client Name",
        enterClientName: "Enter client name",
        // FIX: Added missing translation key.
        enterBudget: "Enter budget",
        phoneNumber1: "Phone Number 1",
        enterPhoneNumber: "Enter phone number",
        assignedTo: "Assigned To",
        decisionMaker: "Decision Maker",
        influencer: "Influencer",
        fresh: "Fresh",
        cold: "Cold",
        high: "High",
        medium: "Medium",
        low: "Low",
        egFacebookAd: "e.g., Facebook Ad",
        // AddActionModal
        for: "for",
        stage: "Stage",
        untouched: "Untouched",
        touched: "Touched",
        following: "Following",
        noAnswer: "No Answer",
        outOfService: "Out Of Service",
        writeActionDetails: "Write details of the action (e.g., call summary)",
        reminderDate: "Reminder Date",
        // AssignLeadModal
        leadsCount: "Leads Count",
        selectEmployee: "Select Employee",
        // FilterDrawer
        filterLeads: "Filter Leads",
        teamLeader: "Team Leader",
        selectLeader: "Select leader",
        assigned: "Assigned",
        selectAssignedOrNot: "Select is assigned or not",
        unassigned: "Unassigned",
        selectUser: "Select user",
        selectAuthority: "Select authority",
        leadInfo: "Lead Info",
        selectProject: "Select project",
        selectCampaign: "Select campaign",
        selectChannel: "Select channel",
        qualified: "Qualified",
        unqualified: "Unqualified",
        cancelReasons: "Cancel Reasons",
        selectCancelReason: "Select cancel reason",
        budgetTooHigh: "Budget too high",
        notInterested: "Not interested",
        currentStage: "Current Stage",
        selectStage: "Select stage",
        hasStages: "Has Stages",
        selectStages: "Select stages",
        selectPriority: "Select priority",
        excelFilenames: "Excel Filenames",
        selectExcel: "Select excel",
        budgetRangeStart: "Budget Range Start",
        eg500000: "e.g., 500000",
        budgetRangeEnd: "Budget Range End",
        eg1000000: "e.g., 1000000",
        delay: "Delay",
        delayedReminderLeads: "Delayed Reminder Leads",
        selectDelayedOrNot: "Select delayed or not",
        delayed: "Delayed",
        notDelayed: "Not Delayed",
        dateAddedRange: "Date Added Range",
        dateAssignedRange: "Date Assigned Range",
        lastActionRange: "Last Action Range",
        reminderDateRange: "Reminder Date Range",
        // UnitsFilterDrawer
        filterUnits: "Filter Units",
        filters: "Filters",
        selectBedrooms: "Select Bedrooms",
        selectBathrooms: "Select Bathrooms",
        selectType: "Select Type",
        apartment: "Apartment",
        villa: "Villa",
        finishingType: "Finishing type",
        selectFinishing: "Select Finishing",
        finished: "Finished",
        semiFinished: "Semi-Finished",
        selectCity: "Select City",
        selectDistrict: "Select District",
        selectZone: "Select Zone",
        eg2000000: "e.g., 2000000",
        sold: "Sold",
        // AddDeveloperModal
        addNewDeveloper: "Add New Developer",
        developerName: "Developer Name",
        enterDeveloperName: "Enter developer name",
        enterCode: "Enter code",
        // AddProjectModal
        addNewProject: "Add New Project",
        projectName: "Project Name",
        enterProjectName: "Enter project name",
        // AddUnitModal
        addNewUnit: "Add New Unit",
        unitCode: "Unit Code",
        enterUnitCode: "Enter unit code",
        // AddOwnerModal
        addNewOwner: "Add New Owner",
        ownerName: "Owner name",
        enterOwnerFullName: "Enter owner's full name",
        ownerCode: "Owner code",
        enterUniqueCode: "Enter a unique code",
        ownerPhone: "Owner phone",
        enterContactPhoneNumber: "Enter contact phone number",
        selectCityPlaceholder: "Select city...",
        riyadh: "Riyadh",
        jeddah: "Jeddah",
        dammam: "Dammam",
        ownerDistrict: "Owner district",
        enterSpecificDistrict: "Enter the specific district",
        // DealsFilterDrawer
        filterDeals: "Filter Deals",
        addedBy: "Added By",
        dealInfo: "Deal Info",
        selectStatus: "Select status",
        reservation: "Reservation",
        contracted: "Contracted",
        // closed: "Closed", // This key already exists
        selectMethod: "Select method",
        cash: "Cash",
        installment: "Installment",
        selectUnit: "Select unit",
        leadChannel: "Lead Channel",
        google: "Google",
        leadCampaign: "Lead Campaign",
        datesAndDuration: "Dates & Duration",
        leadCreatedAtRange: "lead created at range",
        dealCreatedAtRange: "Deal created At range",
        durationDays: "Duration (days)",
        eg30: "e.g. 30",
        // EditUserModal
        newUserPassword: "New Password",
        leaveBlankPassword: "Leave blank to keep current password",
        salesManager: "Sales Manager",
        salesAgent: "Sales Agent",
        saveChanges: "Save Changes",
        // DeleteUserModal
        confirmDeleteUser1: "Are you sure you want to delete the user",
        confirmDeleteUser2: "? This action cannot be undone.",
        // AddCampaignModal
        addNewCampaign: "Add New Campaign",
        enterCampaignName: "Enter campaign name",
        enterCampaignCode: "Enter campaign code",
        enterCampaignBudget: "Enter campaign budget",
        // AddIntegrationAccountModal
        addNew: "Add New",
        account: "Account",
        accountName: "Account Name",
        enterAccountName: "Enter account name",
        accountLink: "Account Link",
        egSalesWhatsapp: "e.g., Sales WhatsApp",
        phoneNumber: "Phone Number",
        enterWhatsappNumber: "Enter WhatsApp number",
        connected: "Connected",
        disconnected: "Disconnected",
        // ChangePasswordModal
        changePassword: "Change Password",
        currentPassword: "Current Password",
        enterCurrentPassword: "Enter current password",
        newPassword: "New Password",
        enterNewPassword: "Enter new password",
        confirmNewPassword: "Confirm New Password",
        enterConfirmNewPassword: "Enter new password again",
        // Profile
        profile: "Profile",
        profileSettings: "Profile Settings",
        siteCustomization: "Site Customization",
        primaryColor: "Primary Color",
        activeSubPageColor: "Active Sub-Page Color",
        siteLogo: "Site Logo",
        profilePicture: "Profile Picture",
        upload: "Upload",
        security: "Security",
        saveProfile: "Save Profile",
    },
    ar: {
        hello: "أهلاً بك في نظام ديل! 👋",
        welcomeBack: "مرحبا بعودتك!",
        signInToContinue: "سجل الدخول للمتابعة وإدارة علاقات عملائك بكفاءة.",
        crmWelcome: "مستقبل إدارة علاقات العملاء.",
        crmDescription: "أتمتة المهام المتكررة، تعزيز الإنتاجية، وتحسين سير عملك مع نظامنا البديهي لإدارة علاقات العملاء.",
        username: "اسم المستخدم",
        password: "كلمة المرور",
        signIn: "تسجيل الدخول",
        pleaseEnterCredentials: "الرجاء إدخال اسم المستخدم وكلمة المرور",
        invalidCredentials: "اسم المستخدم أو كلمة المرور غير صحيحة",
        search: "بحث",
        searchEllipsis: "بحث...",
        all: "الكل",
        user: "المستخدم",
        // Sidebar
        dashboard: "لوحة التحكم",
        leads: "العملاء المحتملون",
        allLeads: "كل العملاء",
        freshLeads: "عملاء جدد",
        coldLeads: "عملاء باردون",
        myLeads: "عملائي",
        rotatedLeads: "عملاء معاد توجيههم",
        activities: "الأنشطة",
        inventory: "المخزون",
        properties: "العقارات",
        owners: "الملاك",
        deals: "الصفقات",
        users: "المستخدمون",
        marketing: "التسويق",
        campaigns: "الحملات",
        // FIX: Added missing translation key.
        campaign: "الحملة",
        todos: "المهام",
        reports: "التقارير",
        teamsReport: "تقرير الفرق",
        employeesReport: "تقرير الموظفين",
        marketingReport: "تقرير التسويق",
        integrations: "التكاملات",
        meta: "Meta",
        facebook: "فيسبوك", // Keep for backward compatibility with data
        tikTok: "تيك توك",
        whatsApp: "واتساب",
        // FIX: Added missing translation key.
        website: "الموقع الإلكتروني",
        settings: "الإعدادات",
        channels: "القنوات",
        stages: "المراحل",
        statuses: "الحالات",
        logout: "تسجيل الخروج",
        // Dashboard
        todayNewLeads: "عملاء محتملون جدد اليوم",
        todayTouchedLeads: "عملاء تم التواصل معهم اليوم",
        todayUntouchedLeads: "عملاء لم يتم التواصل معهم اليوم",
        delayedLeads: "عملاء متأخرون",
        weekLeadsReport: "تقرير العملاء الأسبوعي",
        stagesReport: "تقرير المراحل",
        topUsers: "أفضل المستخدمين",
        latestFeedbacks: "آخر الملاحظات",
        noDataAvailable: "لا توجد بيانات متاحة",
        // Leads
        filter: "تصفية",
        addLead: "إضافة عميل",
        assignLead: "إسناد عميل",
        name: "الاسم",
        phone: "الهاتف",
        actions: "إجراءات",
        lastFeedback: "آخر ملاحظة",
        notes: "ملاحظات",
        lastStage: "آخر مرحلة",
        reminder: "تذكير",
        view: "عرض",
        add_action: "إضافة إجراء",
        // View Lead
        unassign: "إلغاء الإسناد",
        addDeal: "إضافة صفقة",
        editClient: "تعديل العميل",
        details: "التفاصيل",
        communicationWay: "طريقة التواصل",
        authority: "الصلاحية",
        priority: "الأولوية",
        dates: "التواريخ",
        createdAt: "تاريخ الإنشاء",
        timeline: "السجل الزمني",
        // Activities
        allUsers: "كل المستخدمين",
        today: "اليوم",
        yesterday: "الأمس",
        last7Days: "آخر 7 أيام",
        thisMonth: "هذا الشهر",
        allLeadsType: "كل أنواع العملاء",
        freshLead: "عميل جديد",
        coldLead: "عميل بارد",
        call: "مكالمة",
        meeting: "اجتماع",
        whatsapp: "واتساب",
        note: "ملاحظة",
        lead: "العميل",
        type: "النوع",
        date: "التاريخ",
        noActivitiesFound: "لم يتم العثور على أنشطة للمرشحات المحددة.",
        // Properties
        createNew: "إنشاء جديد",
        addDeveloper: "إضافة مطور",
        addProject: "إضافة مشروع",
        addUnit: "إضافة وحدة",
        // Services
        services: "الخدمات",
        servicePackages: "باقات الخدمات",
        serviceProviders: "مقدمي الخدمات",
        duration: "المدة",
        rating: "التقييم",
        // Products
        products: "المنتجات",
        productCategories: "فئات المنتجات",
        suppliers: "الموردون",
        cost: "التكلفة",
        stock: "المخزون",
        sku: "رمز المنتج",
        contactPerson: "الشخص المسؤول",
        specialization: "التخصص",
        realEstateOnly: "هذه الصفحة متاحة فقط لشركات العقارات.",
        servicesOnly: "هذه الصفحة متاحة فقط لشركات الخدمات.",
        productsOnly: "هذه الصفحة متاحة فقط لشركات المنتجات.",
        active: "نشط",
        inactive: "غير نشط",
        units: "الوحدات",
        projects: "المشاريع",
        developers: "المطورون",
        searchUnits: "بحث في الوحدات",
        noUnitsFound: "لم يتم العثور على وحدات.",
        logo: "الشعار",
        developer: "المطور",
        city: "المدينة",
        paymentMethod: "طريقة الدفع",
        update: "تحديث",
        delete: "حذف",
        bedrooms: "غرف النوم",
        // FIX: Added missing translation key.
        bathrooms: "الحمامات",
        price: "السعر",
        // Owners
        addOwner: "إضافة مالك",
        district: "الحي",
        // FIX: Added missing translation key.
        zone: "المنطقة",
        noOwnersFound: "لم يتم العثور على ملاك.",
        // Deals
        searchDeals: "بحث في الصفقات",
        createDeal: "إنشاء صفقة",
        dealId: "المعرف",
        value: "القيمة",
        // Create Deal
        createNewDeal: "إنشاء صفقة جديدة",
        dealInformation: "معلومات الصفقة",
        project: "المشروع",
        startedBy: "بدأت بواسطة",
        closedBy: "أغلقت بواسطة",
        startDate: "تاريخ البدء",
        closedDate: "تاريخ الإغلاق",
        discountPercentage: "نسبة الخصم",
        discountAmount: "مبلغ الخصم",
        totalValue: "القيمة الإجمالية",
        salesCommissionPercentage: "نسبة عمولة المبيعات",
        salesCommissionAmount: "مبلغ عمولة المبيعات",
        description: "الوصف",
        // Users
        autoAssignment: "الإسناد التلقائي",
        on: "مفعل",
        off: "معطل",
        viewUser: "عرض المستخدم",
        createUser: "إنشاء مستخدم",
        editUser: "تعديل المستخدم",
        deleteUser: "حذف المستخدم",
        salesAssistant: "مساعد مبيعات",
        owner: "المالك",
        nameRequired: "الاسم مطلوب",
        usernameRequired: "اسم المستخدم مطلوب",
        emailRequired: "البريد الإلكتروني مطلوب",
        passwordRequired: "كلمة المرور مطلوبة",
        phoneRequired: "رقم الهاتف مطلوب",
        roleRequired: "الدور مطلوب",
        invalidEmail: "صيغة البريد الإلكتروني غير صحيحة",
        passwordMinLength: "كلمة المرور يجب أن تكون 6 أحرف على الأقل",
        // Campaigns
        addCampaign: "إضافة حملة",
        isActive: "نشطة",
        yes: "نعم",
        no: "لا",
        noResultsFound: "لم يتم العثور على نتائج.",
        // Todos
        thisWeek: "هذا الأسبوع",
        noTasksForDate: "لا توجد مهام بتاريخ",
        // Reports
        allTeams: "كل الفرق",
        selectFiltersPrompt: "اختر مرشحات لعرض التقرير.",
        totalCalls: "إجمالي المكالمات",
        answered: "تم الرد عليها",
        notAnswered: "لم يتم الرد عليها",
        // Integrations
        integration: "التكامل",
        addNewAccount: "إضافة حساب جديد",
        disconnect: "قطع الاتصال",
        noAccountsConnected: "لا توجد حسابات متصلة",
        connectAccountPrompt: "انقر فوق 'إضافة حساب جديد' لتوصيل صفحتك والبدء في التقاط العملاء المحتملين.",
        // General
        status: "الحالة",
        code: "الرمز",
        budget: "الميزانية",
        role: "الدور",
        email: "البريد الإلكتروني",
        unit: "الوحدة",
        // Settings
        leadAssignmentSettings: "إعدادات إسناد العملاء",
        autoRotation: "تمكين التدوير التلقائي للعملاء المتأخرين",
        autoRotationDesc: "عند التمكين، يقوم النظام تلقائيًا بإعادة تعيين العملاء الذين لم تتم متابعتهم خلال وقت محدد.",
        reminderDelayTime: "وقت تأخير التذكير (بالدقائق)",
        reminderDelayTimeDesc: "يحدد هذا الوقت مدة الانتظار قبل تمييز العميل بأنه 'متأخر'.",
        saveSettings: "حفظ الإعدادات",
        channelAutomation: "أتمتة القنوات",
        multiChannelTracking: "تمكين تتبع العملاء متعددي القنوات",
        defaultChannel: "القناة الافتراضية",
        defaultChannelDesc: "تعيين قناة لأي عملاء جدد بمصدر غير معروف.",
        activeChannels: "القنوات النشطة",
        addChannel: "إضافة قناة",
        channel: "القناة",
        addType: "إضافة نوع",
        typeName: "اسم النوع",
        enterTypeName: "أدخل اسم النوع",
        stageAutomation: "أتمتة المراحل",
        autoStageAdvancement: "تمكين التقدم التلقائي للمرحلة",
        requireStageCompletion: "طلب إكمال المرحلة",
        leadStages: "مراحل العملاء",
        addStage: "إضافة مرحلة",
        stageName: "اسم المرحلة",
        required: "مطلوب",
        autoAdvance: "تقدم تلقائي",
        statusConfiguration: "تكوين الحالة",
        enableCustomStatuses: "تمكين الحالات المخصصة",
        requireStatusUpdates: "طلب تحديثات الحالة",
        defaultActiveStatus: "الحالة النشطة الافتراضية",
        defaultActiveStatusDesc: "تعيين الحالة الافتراضية لجميع العملاء الجدد.",
        availableStatuses: "الحالات المتاحة",
        addStatus: "إضافة حالة",
        category: "الفئة",
        followUp: "متابعة",
        closed: "مغلق",
        // Modals & Drawers general
        submit: "إرسال",
        cancel: "إلغاء",
        reset: "إعادة تعيين",
        applyFilters: "تطبيق الفلاتر",
        edit: "تعديل",
        confirmDelete: "هل أنت متأكد أنك تريد حذف هذا العنصر؟ لا يمكن التراجع عن هذا الإجراء.",
        // AddLeadModal
        addNewLead: "إضافة عميل جديد",
        clientName: "اسم العميل",
        enterClientName: "أدخل اسم العميل",
        // FIX: Added missing translation key.
        enterBudget: "أدخل الميزانية",
        phoneNumber1: "رقم الهاتف 1",
        enterPhoneNumber: "أدخل رقم الهاتف",
        assignedTo: "مسند إلى",
        decisionMaker: "صاحب القرار",
        influencer: "مؤثر",
        fresh: "جديد",
        cold: "بارد",
        high: "مرتفع",
        medium: "متوسط",
        low: "منخفض",
        egFacebookAd: "مثال: إعلان فيسبوك",
        // AddActionModal
        for: "لـ",
        stage: "المرحلة",
        untouched: "لم يلمس",
        touched: "تم اللمس",
        following: "متابعة",
        noAnswer: "لا يوجد رد",
        outOfService: "خارج الخدمة",
        writeActionDetails: "اكتب تفاصيل الإجراء (مثل ملخص المكالمة)",
        reminderDate: "تاريخ التذكير",
        // AssignLeadModal
        leadsCount: "عدد العملاء",
        selectEmployee: "اختر موظف",
        // FilterDrawer
        filterLeads: "تصفية العملاء",
        teamLeader: "قائد الفريق",
        selectLeader: "اختر قائد",
        assigned: "مسند",
        selectAssignedOrNot: "اختر مسند أم لا",
        unassigned: "غير مسند",
        selectUser: "اختر مستخدم",
        selectAuthority: "اختر الصلاحية",
        leadInfo: "معلومات العميل",
        selectProject: "اختر مشروع",
        selectCampaign: "اختر حملة",
        selectChannel: "اختر قناة",
        qualified: "مؤهل",
        unqualified: "غير مؤهل",
        cancelReasons: "أسباب الإلغاء",
        selectCancelReason: "اختر سبب الإلغاء",
        budgetTooHigh: "الميزانية مرتفعة جدا",
        notInterested: "غير مهتم",
        currentStage: "المرحلة الحالية",
        selectStage: "اختر مرحلة",
        hasStages: "لديه مراحل",
        selectStages: "اختر مراحل",
        selectPriority: "اختر الأولوية",
        excelFilenames: "أسماء ملفات Excel",
        selectExcel: "اختر ملف Excel",
        budgetRangeStart: "بداية نطاق الميزانية",
        eg500000: "مثال: 500000",
        budgetRangeEnd: "نهاية نطاق الميزانية",
        eg1000000: "مثال: 1000000",
        delay: "تأخير",
        delayedReminderLeads: "عملاء بتذكير متأخر",
        selectDelayedOrNot: "اختر متأخر أم لا",
        delayed: "متأخر",
        notDelayed: "غير متأخر",
        dateAddedRange: "نطاق تاريخ الإضافة",
        dateAssignedRange: "نطاق تاريخ الإسناد",
        lastActionRange: "نطاق آخر إجراء",
        reminderDateRange: "نطاق تاريخ التذكير",
        // UnitsFilterDrawer
        filterUnits: "تصفية الوحدات",
        filters: "الفلاتر",
        selectBedrooms: "اختر عدد غرف النوم",
        selectBathrooms: "اختر عدد الحمامات",
        selectType: "اختر النوع",
        apartment: "شقة",
        villa: "فيلا",
        finishingType: "نوع التشطيب",
        selectFinishing: "اختر التشطيب",
        finished: "مشطب",
        semiFinished: "نصف تشطيب",
        selectCity: "اختر المدينة",
        selectDistrict: "اختر الحي",
        selectZone: "اختر المنطقة",
        eg2000000: "مثال: 2000000",
        sold: "مباع",
        // AddDeveloperModal
        addNewDeveloper: "إضافة مطور جديد",
        developerName: "اسم المطور",
        enterDeveloperName: "أدخل اسم المطور",
        enterCode: "أدخل الرمز",
        // AddProjectModal
        addNewProject: "إضافة مشروع جديد",
        projectName: "اسم المشروع",
        enterProjectName: "أدخل اسم المشروع",
        // AddUnitModal
        addNewUnit: "إضافة وحدة جديدة",
        unitCode: "رمز الوحدة",
        enterUnitCode: "أدخل رمز الوحدة",
        // AddOwnerModal
        addNewOwner: "إضافة مالك جديد",
        ownerName: "اسم المالك",
        enterOwnerFullName: "أدخل اسم المالك الكامل",
        ownerCode: "رمز المالك",
        enterUniqueCode: "أدخل رمزًا فريدًا",
        ownerPhone: "هاتف المالك",
        enterContactPhoneNumber: "أدخل رقم هاتف الاتصال",
        selectCityPlaceholder: "اختر مدينة...",
        riyadh: "الرياض",
        jeddah: "جدة",
        dammam: "الدمام",
        ownerDistrict: "حي المالك",
        enterSpecificDistrict: "أدخل الحي المحدد",
        // DealsFilterDrawer
        filterDeals: "تصفية الصفقات",
        addedBy: "أضيف بواسطة",
        dealInfo: "معلومات الصفقة",
        selectStatus: "اختر الحالة",
        reservation: "حجز",
        contracted: "تم التعاقد",
        // closed: "مغلق", // This key already exists
        selectMethod: "اختر الطريقة",
        cash: "نقدي",
        installment: "تقسيط",
        selectUnit: "اختر وحدة",
        leadChannel: "قناة العميل",
        google: "جوجل",
        leadCampaign: "حملة العميل",
        datesAndDuration: "التواريخ والمدة",
        leadCreatedAtRange: "نطاق تاريخ إنشاء العميل",
        dealCreatedAtRange: "نطاق تاريخ إنشاء الصفقة",
        durationDays: "المدة (أيام)",
        eg30: "مثال: 30",
        // EditUserModal
        newUserPassword: "كلمة المرور الجديدة",
        leaveBlankPassword: "اتركها فارغة للحفاظ على كلمة المرور الحالية",
        salesManager: "مدير مبيعات",
        salesAgent: "مندوب مبيعات",
        saveChanges: "حفظ التغييرات",
        // DeleteUserModal
        confirmDeleteUser1: "هل أنت متأكد أنك تريد حذف المستخدم",
        confirmDeleteUser2: "؟ لا يمكن التراجع عن هذا الإجراء.",
        // AddCampaignModal
        addNewCampaign: "إضافة حملة جديدة",
        enterCampaignName: "أدخل اسم الحملة",
        enterCampaignCode: "أدخل رمز الحملة",
        enterCampaignBudget: "أدخل ميزانية الحملة",
        // AddIntegrationAccountModal
        addNew: "Add New",
        account: "حساب",
        accountName: "اسم الحساب",
        enterAccountName: "أدخل اسم الحساب",
        accountLink: "رابط الحساب",
        egSalesWhatsapp: "مثال: واتساب المبيعات",
        phoneNumber: "رقم الهاتف",
        enterWhatsappNumber: "أدخل رقم الواتساب",
        connected: "متصل",
        disconnected: "غير متصل",
        // ChangePasswordModal
        changePassword: "تغيير كلمة المرور",
        currentPassword: "كلمة المرور الحالية",
        enterCurrentPassword: "أدخل كلمة المرور الحالية",
        newPassword: "كلمة المرور الجديدة",
        enterNewPassword: "أدخل كلمة المرور الجديدة",
        confirmNewPassword: "تأكيد كلمة المرور الجديدة",
        enterConfirmNewPassword: "أدخل كلمة المرور الجديدة مرة أخرى",
        // Profile
        profile: "الملف الشخصي",
        profileSettings: "إعدادات الملف الشخصي",
        siteCustomization: "تخصيص الموقع",
        primaryColor: "اللون الأساسي",
        activeSubPageColor: "لون الصفحة الفرعية النشط",
        siteLogo: "شعار الموقع",
        profilePicture: "صورة الملف الشخصي",
        upload: "رفع",
        security: "الأمان",
        saveProfile: "حفظ الملف الشخصي",
    }
};