

import React from 'react';
import { Page, Lead, User, Deal, Todo, Campaign, TimelineEntry, Activity, Developer, Project, Unit, Owner, Channel, Stage, Status, Service, ServicePackage, ServiceProvider, Product, ProductCategory, Supplier } from './types';
import { ChartIcon, CheckSquareIcon, ChevronsUpDownIcon, FileTextIcon, HandshakeIcon, MegaphoneIcon, SettingsIcon, ShoppingBagIcon, StarIcon, TargetIcon, UsersIcon } from './components/index';

export const SIDEBAR_ITEMS: { 
  name: Page; 
  icon: React.FC<React.SVGProps<SVGSVGElement>>; 
  subItems?: Page[] 
}[] = [
  { name: 'Dashboard', icon: ChartIcon },
  { name: 'Leads', icon: TargetIcon, subItems: ['All Leads', 'Fresh Leads', 'Cold Leads', 'My Leads', 'Rotated Leads'] },
  { name: 'Activities', icon: StarIcon },
  { name: 'Inventory', icon: ShoppingBagIcon, subItems: ['Properties', 'Owners'] },
  { name: 'Deals', icon: HandshakeIcon },
  { name: 'Users', icon: UsersIcon },
  { name: 'Marketing', icon: MegaphoneIcon, subItems: ['Campaigns'] },
  { name: 'Todos', icon: CheckSquareIcon },
  { name: 'Reports', icon: FileTextIcon, subItems: ['Teams Report', 'Employees Report', 'Marketing Report'] },
  { name: 'Integrations', icon: ChevronsUpDownIcon, subItems: ['Meta', 'TikTok', 'WhatsApp'] },
];

export const SETTINGS_ITEM = { name: 'Settings', icon: SettingsIcon };


export const translations = {
    en: {
        hello: "Hello LOOP CRM! 👋",
        welcomeBack: "Welcome Back!",
        signInToContinue: "Sign in to continue managing your customer relationships efficiently.",
        crmWelcome: "The future of customer relationship management.",
        crmDescription: "Automate repetitive tasks, enhance productivity, and improve your workflows with our intuitive CRM.",
        username: "Username",
        password: "Password",
        signIn: "Sign In",
        pleaseEnterCredentials: "Please enter username and password",
        invalidCredentials: "Invalid username or password",
        loginErrorNoActiveAccount: "No active account found with the given credentials",
        loginErrorUnableToLogin: "Unable to log in with provided credentials",
        loginErrorAccountInactive: "Account is inactive",
        loginErrorInvalidCredentials: "Invalid username or password",
        search: "Search",
        searchEllipsis: "Search...",
        all: "All",
        user: "User",
        // Sidebar
        dashboard: "Dashboard",
        leads: "Leads",
        allLeads: "All Leads",
        freshLeads: "Fresh Leads",
        coldLeads: "Cold Leads",
        myLeads: "My Leads",
        rotatedLeads: "Rotated Leads",
        activities: "Activities",
        inventory: "Inventory",
        properties: "Properties",
        owners: "Owners",
        deals: "Deals",
        users: "Users",
        marketing: "Marketing",
        campaigns: "Campaigns",
        // FIX: Added missing translation key.
        campaign: "Campaign",
        todos: "Todos",
        reports: "Reports",
        teamsReport: "Teams Report",
        employeesReport: "Employees Report",
        marketingReport: "Marketing Report",
        integrations: "Integrations",
        meta: "Meta",
        facebook: "Facebook", // Keep for backward compatibility with data
        tikTok: "TikTok",
        whatsApp: "WhatsApp",
        // FIX: Added missing translation key.
        website: "Website",
        settings: "Settings",
        channels: "Channels",
        stages: "Stages",
        statuses: "Statuses",
        logout: "Logout",
        logoutConfirmTitle: "Confirm Logout",
        logoutConfirmMessage: "Are you sure you want to log out?",
        // Dashboard
        todayNewLeads: "Today New Leads",
        todayTouchedLeads: "Today Touched Leads",
        todayUntouchedLeads: "Today Untouched Leads",
        delayedLeads: "Delayed Leads",
        weekLeadsReport: "Week Leads Report",
        last7DaysPerformance: "Last 7 days performance",
        stagesReport: "Stages Report",
        distributionByStage: "Distribution by stage",
        topUsers: "Top Users",
        mostActivePerformers: "Most active performers",
        latestFeedbacks: "Latest Feedbacks",
        recentActivityUpdates: "Recent activity updates",
        noDataAvailable: "No data available",
        noStageDataAvailable: "No stage data available",
        noUserActivityData: "No user activity data",
        noRecentFeedbackAvailable: "No recent feedback available",
        noNotes: "No notes",
        totalLeads: "Total Leads",
        totalDeals: "Total Deals",
        activeTodos: "Active Todos",
        completedDeals: "Completed Deals",
        // Leads
        filter: "Filter",
        addLead: "Add Lead",
        assignLead: "Assign Lead",
        name: "Name",
        phone: "Phone",
        actions: "Actions",
        lastFeedback: "Last Feedback",
        notes: "Notes",
        lastStage: "Last Stage",
        reminder: "Reminder",
        view: "View",
        add_action: "Add Action",
        // View Lead
        unassign: "Unassign",
        addDeal: "Add Deal",
        editClient: "Edit Client",
        details: "Details",
        communicationWay: "Communication Way",
        authority: "Authority",
        priority: "Priority",
        dates: "Dates",
        createdAt: "Created At",
        timeline: "Timeline",
        // Activities
        allUsers: "All users",
        today: "Today",
        yesterday: "Yesterday",
        last7Days: "Last 7 Days",
        thisMonth: "This Month",
        allLeadsType: "All Leads Type",
        freshLead: "Fresh Lead",
        coldLead: "Cold Lead",
        call: "Call",
        meeting: "Meeting",
        whatsapp: "Whatsapp",
        note: "Note",
        lead: "Lead",
        type: "Type",
        date: "Date",
        noActivitiesFound: "No activities found for the selected filters.",
        // Properties
        createNew: "Create New",
        addDeveloper: "Add Developer",
        addProject: "Add Project",
        addUnit: "Add Unit",
        // Services
        services: "Services",
        servicePackages: "Service Packages",
        serviceProviders: "Service Providers",
        duration: "Duration",
        rating: "Rating",
        // Products
        products: "Products",
        productCategories: "Product Categories",
        suppliers: "Suppliers",
        cost: "Cost",
        stock: "Stock",
        sku: "SKU",
        contactPerson: "Contact Person",
        specialization: "Specialization",
        realEstateOnly: "This page is only available for Real Estate companies.",
        servicesOnly: "This page is only available for Services companies.",
        productsOnly: "This page is only available for Products companies.",
        active: "Active",
        inactive: "Inactive",
        units: "Units",
        projects: "Projects",
        developers: "Developers",
        searchUnits: "Search Units",
        noUnitsFound: "No units found.",
        logo: "Logo",
        developer: "Developer",
        city: "City",
        paymentMethod: "Payment Method",
        update: "Update",
        delete: "Delete",
        bedrooms: "Bedrooms",
        // FIX: Added missing translation key.
        bathrooms: "Bathrooms",
        price: "Price",
        // Owners
        addOwner: "Add Owner",
        district: "District",
        // FIX: Added missing translation key.
        zone: "Zone",
        noOwnersFound: "No owners found.",
        // Deals
        searchDeals: "Search Deals",
        createDeal: "Create Deal",
        dealId: "ID",
        value: "Value",
        // Create Deal
        createNewDeal: "Create New Deal",
        dealInformation: "Deal Information",
        project: "Project",
        startedBy: "Started By",
        closedBy: "Closed By",
        startDate: "Start Date",
        closedDate: "Closed Date",
        discountPercentage: "Discount Percentage",
        discountAmount: "Discount Amount",
        totalValue: "Total Value",
        salesCommissionPercentage: "Sales Commission Percentage",
        salesCommissionAmount: "Sales Commission Amount",
        description: "Description",
        unknownClient: "Unknown Client",
        eg1000000: "e.g. 1000000",
        eg10: "e.g. 10",
        calculated: "Calculated",
        eg25: "e.g. 2.5",
        enterNotesAboutDeal: "Enter any notes about the deal...",
        // Users
        autoAssignment: "Auto Assignment",
        on: "On",
        off: "Off",
        viewUser: "View User",
        createUser: "Create User",
        editUser: "Edit User",
        deleteUser: "Delete User",
        salesAssistant: "Sales Assistant",
        owner: "Owner",
        noPhoneNumber: "No phone number available",
        nameRequired: "Name is required",
        usernameRequired: "Username is required",
        emailRequired: "Email is required",
        passwordRequired: "Password is required",
        phoneRequired: "Phone is required",
        enterPhone: "Enter phone number",
        invalidPhone: "Invalid phone number format",
        roleRequired: "Role is required",
        invalidEmail: "Invalid email format",
        passwordMinLength: "Password must be at least 6 characters",
        // Campaigns
        addCampaign: "Add Campaign",
        isActive: "Is Active",
        yes: "Yes",
        no: "No",
        noResultsFound: "No results found.",
        // Todos
        addTodo: "Add Todo",
        thisWeek: "This Week",
        noTasksForDate: "No tasks for",
        failedToCompleteTodo: "Failed to complete todo. Please try again.",
        completed: "Completed",
        // Reports
        allTeams: "All Teams",
        selectFiltersPrompt: "Select filters to view the report.",
        totalCalls: "Total calls",
        answered: "Answered",
        notAnswered: "Not Answered",
        // Integrations
        integration: "Integration",
        addNewAccount: "Add New Account",
        disconnect: "Disconnect",
        noAccountsConnected: "No accounts connected",
        connectAccountPrompt: "Click 'Add New Account' to connect your page and start capturing leads.",
        // General
        status: "Status",
        code: "Code",
        budget: "Budget",
        role: "Role",
        email: "Email",
        unit: "Unit",
        // Settings
        leadAssignmentSettings: "Lead Assignment Settings",
        autoRotation: "Enable Auto Rotation for Delayed Leads",
        autoRotationDesc: "When enabled, the system automatically reassigns leads that have not been attended to within a specified time.",
        reminderDelayTime: "Reminder Delay Time (Minutes)",
        reminderDelayTimeDesc: "This time determines how long to wait before a lead is marked as 'delayed'.",
        saveSettings: "Save Settings",
        channelAutomation: "Channel Automation",
        multiChannelTracking: "Enable Multi-Channel Lead Tracking",
        defaultChannel: "Default Channel",
        defaultChannelDesc: "Assign a channel to any new leads with an unknown source.",
        activeChannels: "Active Channels",
        addChannel: "Add Channel",
        channel: "Channel",
        addType: "Add Type",
        typeName: "Type Name",
        enterTypeName: "Enter type name",
        stageAutomation: "Stage Automation",
        autoStageAdvancement: "Enable Auto Stage Advancement",
        requireStageCompletion: "Require Stage Completion",
        leadStages: "Lead Stages",
        addStage: "Add Stage",
        stageName: "Stage Name",
        required: "Required",
        autoAdvance: "Auto Advance",
        statusConfiguration: "Status Configuration",
        enableCustomStatuses: "Enable Custom Statuses",
        requireStatusUpdates: "Require Status Updates",
        defaultActiveStatus: "Default Active Status",
        defaultActiveStatusDesc: "Set the default status for all new leads.",
        availableStatuses: "Available Statuses",
        addStatus: "Add Status",
        category: "Category",
        followUp: "Follow Up",
        closed: "Closed",
        // Modals & Drawers general
        submit: "Submit",
        cancel: "Cancel",
        reset: "Reset",
        applyFilters: "Apply Filters",
        edit: "Edit",
        confirmDelete: "Are you sure you want to delete this item? This action cannot be undone.",
        // AddLeadModal
        addNewLead: "Add New Lead",
        clientName: "Client Name",
        enterClientName: "Enter client name",
        // FIX: Added missing translation key.
        enterBudget: "Enter budget",
        phoneNumber1: "Phone Number 1",
        enterPhoneNumber: "Enter phone number",
        assignedTo: "Assigned To",
        decisionMaker: "Decision Maker",
        influencer: "Influencer",
        fresh: "Fresh",
        cold: "Cold",
        high: "High",
        medium: "Medium",
        low: "Low",
        egFacebookAd: "e.g., Facebook Ad",
        // AddActionModal
        for: "for",
        stage: "Stage",
        untouched: "Untouched",
        touched: "Touched",
        following: "Following",
        noAnswer: "No Answer",
        outOfService: "Out Of Service",
        // Task Stages
        hold: "Hold",
        doneMeeting: "Done Meeting",
        followAfterMeeting: "Follow After Meeting",
        rescheduleMeeting: "Reschedule Meeting",
        cancellation: "Cancellation",
        notInterested: "Not Interested",
        whatsappPending: "WhatsApp Pending",
        broker: "Broker",
        resale: "Resale",
        // AddTodoModal
        deal: "Deal",
        selectDeal: "Select Deal",
        reminderDateAndTime: "Reminder Date & Time",
        enterNotes: "Enter notes...",
        loading: "Loading...",
        pleaseFillRequiredFields: "Please fill in required fields",
        failedToCreateTodo: "Failed to create todo. Please try again.",
        writeActionDetails: "Write details of the action (e.g., call summary)",
        reminderDate: "Reminder Date",
        stageUpdated: "Stage updated",
        // AssignLeadModal
        leadsCount: "Leads Count",
        selectEmployee: "Select Employee",
        // FilterDrawer
        filterLeads: "Filter Leads",
        teamLeader: "Team Leader",
        selectLeader: "Select leader",
        assigned: "Assigned",
        selectAssignedOrNot: "Select is assigned or not",
        unassigned: "Unassigned",
        selectUser: "Select user",
        selectLead: "Select Lead",
        selectAuthority: "Select authority",
        leadInfo: "Lead Info",
        selectProject: "Select project",
        selectCampaign: "Select campaign",
        selectChannel: "Select channel",
        qualified: "Qualified",
        unqualified: "Unqualified",
        cancelReasons: "Cancel Reasons",
        selectCancelReason: "Select cancel reason",
        budgetTooHigh: "Budget too high",
        currentStage: "Current Stage",
        selectStage: "Select stage",
        hasStages: "Has Stages",
        selectStages: "Select stages",
        selectPriority: "Select priority",
        excelFilenames: "Excel Filenames",
        selectExcel: "Select excel",
        budgetRangeStart: "Budget Range Start",
        eg500000: "e.g., 500000",
        budgetRangeEnd: "Budget Range End",
        delay: "Delay",
        delayedReminderLeads: "Delayed Reminder Leads",
        selectDelayedOrNot: "Select delayed or not",
        delayed: "Delayed",
        notDelayed: "Not Delayed",
        dateAddedRange: "Date Added Range",
        dateAssignedRange: "Date Assigned Range",
        lastActionRange: "Last Action Range",
        reminderDateRange: "Reminder Date Range",
        // UnitsFilterDrawer
        filterUnits: "Filter Units",
        filters: "Filters",
        selectBedrooms: "Select Bedrooms",
        selectBathrooms: "Select Bathrooms",
        selectType: "Select Type",
        apartment: "Apartment",
        villa: "Villa",
        finishingType: "Finishing type",
        selectFinishing: "Select Finishing",
        finished: "Finished",
        semiFinished: "Semi-Finished",
        selectCity: "Select City",
        selectDistrict: "Select District",
        selectZone: "Select Zone",
        eg2000000: "e.g., 2000000",
        sold: "Sold",
        // AddDeveloperModal
        addNewDeveloper: "Add New Developer",
        developerName: "Developer Name",
        enterDeveloperName: "Enter developer name",
        enterCode: "Enter code",
        // AddProjectModal
        addNewProject: "Add New Project",
        projectName: "Project Name",
        enterProjectName: "Enter project name",
        // AddUnitModal
        addNewUnit: "Add New Unit",
        unitCode: "Unit Code",
        enterUnitCode: "Enter unit code",
        // AddOwnerModal
        addNewOwner: "Add New Owner",
        ownerName: "Owner name",
        enterOwnerFullName: "Enter owner's full name",
        ownerCode: "Owner code",
        enterUniqueCode: "Enter a unique code",
        ownerPhone: "Owner phone",
        enterContactPhoneNumber: "Enter contact phone number",
        selectCityPlaceholder: "Select city...",
        riyadh: "Riyadh",
        jeddah: "Jeddah",
        dammam: "Dammam",
        ownerDistrict: "Owner district",
        enterSpecificDistrict: "Enter the specific district",
        // DealsFilterDrawer
        filterDeals: "Filter Deals",
        addedBy: "Added By",
        dealInfo: "Deal Info",
        selectStatus: "Select status",
        reservation: "Reservation",
        contracted: "Contracted",
        // closed: "Closed", // This key already exists
        selectMethod: "Select method",
        cash: "Cash",
        installment: "Installment",
        selectUnit: "Select unit",
        leadChannel: "Lead Channel",
        google: "Google",
        leadCampaign: "Lead Campaign",
        datesAndDuration: "Dates & Duration",
        leadCreatedAtRange: "lead created at range",
        dealCreatedAtRange: "Deal created At range",
        durationDays: "Duration (days)",
        eg30: "e.g. 30",
        // EditUserModal
        newUserPassword: "New Password",
        leaveBlankPassword: "Leave blank to keep current password",
        salesManager: "Sales Manager",
        salesAgent: "Sales Agent",
        saveChanges: "Save Changes",
        // DeleteUserModal
        confirmDeleteUser1: "Are you sure you want to delete the user",
        confirmDeleteUser2: "? This action cannot be undone.",
        errorUpdatingUser: "Failed to update user. Please try again.",
        // AddCampaignModal
        addNewCampaign: "Add New Campaign",
        enterCampaignName: "Enter campaign name",
        enterCampaignCode: "Enter campaign code",
        enterCampaignBudget: "Enter campaign budget",
        // AddIntegrationAccountModal
        addNew: "Add New",
        account: "Account",
        accountName: "Account Name",
        enterAccountName: "Enter account name",
        accountLink: "Account Link",
        egSalesWhatsapp: "e.g., Sales WhatsApp",
        phoneNumber: "Phone Number",
        enterWhatsappNumber: "Enter WhatsApp number",
        connected: "Connected",
        disconnected: "Disconnected",
        // ChangePasswordModal
        changePassword: "Change Password",
        currentPassword: "Current Password",
        enterCurrentPassword: "Enter current password",
        newPassword: "New Password",
        enterNewPassword: "Enter new password",
        confirmNewPassword: "Confirm New Password",
        enterConfirmNewPassword: "Enter new password again",
        currentPasswordRequired: "Current password is required",
        newPasswordRequired: "New password is required",
        confirmPasswordRequired: "Confirm password is required",
        passwordsDoNotMatch: "Passwords do not match",
        newPasswordMustBeDifferent: "New password must be different from current password",
        passwordChangedSuccessfully: "Password changed successfully!",
        errorChangingPassword: "Error changing password",
        changing: "Changing...",
        // Profile
        profile: "Profile",
        profileSettings: "Profile Settings",
        siteCustomization: "Site Customization",
        primaryColor: "Primary Color",
        activeSubPageColor: "Active Sub-Page Color",
        siteLogo: "Site Logo",
        profilePicture: "Profile Picture",
        upload: "Upload",
        security: "Security",
        saveProfile: "Save Profile",
        // Delete modals
        deleteChannel: "Delete Channel",
        confirmDeleteChannel: "Are you sure you want to delete",
        deleteStage: "Delete Stage",
        confirmDeleteStage: "Are you sure you want to delete",
        deleteStatus: "Delete Status",
        confirmDeleteStatus: "Are you sure you want to delete",
        cannotDeleteDefault: "Cannot delete default status",
        // Registration
        register: "Register",
        dontHaveAccount: "Don't have an account?",
        alreadyHaveAccount: "Already have an account?",
        createAccount: "Create Your Account",
        registerDescription: "Start managing your business with our powerful CRM system. Get started in minutes.",
        createCompanyAccount: "Create your company account",
        registrationFailed: "Registration failed. Please try again.",
        networkError: "Network error: Unable to connect to the server. Please check your internet connection and ensure the API server is accessible.",
        companyInformation: "Company Information",
        companyName: "Company Name",
        enterCompanyName: "Enter company name",
        companyNameRequired: "Company name is required",
        companyDomain: "Company Domain",
        enterCompanyDomain: "e.g., example.com",
        companyDomainRequired: "Company domain is required",
        invalidDomain: "Invalid domain format",
        domainHint: "This will be used as your company identifier",
        realEstate: "Real Estate",
        ownerInformation: "Owner Information",
        firstName: "First Name",
        enterFirstName: "Enter first name",
        firstNameRequired: "First name is required",
        lastName: "Last Name",
        enterLastName: "Enter last name",
        lastNameRequired: "Last name is required",
        enterEmail: "Enter email address",
        enterUsername: "Enter username",
        usernameMinLength: "Username must be at least 3 characters",
        enterPassword: "Enter password",
        confirmPassword: "Confirm Password",
        selectPlan: "Select a Plan",
        planSelectionHint: "You can start with a free trial and choose a plan later",
        freeTrial: "Free Trial",
        trialDescription: "14 days free trial, no credit card required",
        free: "Free",
        plansWillBeAdded: "Plans will be available after registration",
        back: "Back",
        next: "Next",
    },
    ar: {
        hello: "أهلاً بك! 👋",
        welcomeBack: "مرحبا بعودتك!",
        signInToContinue: "سجل الدخول للمتابعة وإدارة علاقات عملائك بكفاءة.",
        crmWelcome: "مستقبل إدارة علاقات العملاء.",
        crmDescription: "أتمتة المهام المتكررة، تعزيز الإنتاجية، وتحسين سير عملك مع نظامنا البديهي لإدارة علاقات العملاء.",
        username: "اسم المستخدم",
        password: "كلمة المرور",
        signIn: "تسجيل الدخول",
        pleaseEnterCredentials: "الرجاء إدخال اسم المستخدم وكلمة المرور",
        invalidCredentials: "اسم المستخدم أو كلمة المرور غير صحيحة",
        loginErrorNoActiveAccount: "لم يتم العثور على حساب نشط بالبيانات المقدمة",
        loginErrorUnableToLogin: "تعذر تسجيل الدخول بالبيانات المقدمة",
        loginErrorAccountInactive: "الحساب غير نشط",
        loginErrorInvalidCredentials: "اسم المستخدم أو كلمة المرور غير صحيحة",
        search: "بحث",
        searchEllipsis: "بحث...",
        all: "الكل",
        user: "المستخدم",
        // Sidebar
        dashboard: "لوحة التحكم",
        leads: "العملاء المحتملون",
        allLeads: "كل العملاء",
        freshLeads: "عملاء جدد",
        coldLeads: "عملاء باردون",
        myLeads: "عملائي",
        rotatedLeads: "عملاء معاد توجيههم",
        activities: "الأنشطة",
        inventory: "المخزون",
        properties: "العقارات",
        owners: "المالك",
        deals: "الصفقات",
        users: "المستخدمون",
        marketing: "التسويق",
        campaigns: "الحملات",
        // FIX: Added missing translation key.
        campaign: "الحملة",
        todos: "المهام",
        reports: "التقارير",
        teamsReport: "تقرير الفرق",
        employeesReport: "تقرير الموظفين",
        marketingReport: "تقرير التسويق",
        integrations: "التكاملات",
        meta: "ميتا",
        facebook: "فيسبوك", // Keep for backward compatibility with data
        tikTok: "تيك توك",
        whatsApp: "واتساب",
        // FIX: Added missing translation key.
        website: "الموقع الإلكتروني",
        settings: "الإعدادات",
        channels: "القنوات",
        stages: "المراحل",
        statuses: "الحالات",
        logout: "تسجيل الخروج",
        logoutConfirmTitle: "تأكيد تسجيل الخروج",
        logoutConfirmMessage: "هل أنت متأكد أنك تريد تسجيل الخروج؟",
        // Dashboard
        todayNewLeads: "عملاء محتملون جدد اليوم",
        todayTouchedLeads: "عملاء تم التواصل معهم اليوم",
        todayUntouchedLeads: "عملاء لم يتم التواصل معهم اليوم",
        delayedLeads: "عملاء متأخرون",
        weekLeadsReport: "تقرير العملاء الأسبوعي",
        last7DaysPerformance: "أداء آخر 7 أيام",
        stagesReport: "تقرير المراحل",
        distributionByStage: "التوزيع حسب المرحلة",
        topUsers: "أفضل المستخدمين",
        mostActivePerformers: "الأكثر نشاطاً",
        latestFeedbacks: "آخر الملاحظات",
        recentActivityUpdates: "تحديثات الأنشطة الأخيرة",
        noDataAvailable: "لا توجد بيانات متاحة",
        noStageDataAvailable: "لا توجد بيانات مراحل متاحة",
        noUserActivityData: "لا توجد بيانات نشاط المستخدمين",
        noRecentFeedbackAvailable: "لا توجد ملاحظات حديثة متاحة",
        noNotes: "لا توجد ملاحظات",
        totalLeads: "إجمالي العملاء",
        totalDeals: "إجمالي الصفقات",
        activeTodos: "المهام النشطة",
        completedDeals: "الصفقات المكتملة",
        // Leads
        filter: "تصفية",
        addLead: "إضافة عميل",
        assignLead: "إسناد عميل",
        name: "الاسم",
        phone: "الهاتف",
        actions: "إجراءات",
        lastFeedback: "آخر ملاحظة",
        notes: "ملاحظات",
        lastStage: "آخر مرحلة",
        reminder: "تذكير",
        view: "عرض",
        add_action: "إضافة إجراء",
        // View Lead
        unassign: "إلغاء الإسناد",
        addDeal: "إضافة صفقة",
        editClient: "تعديل العميل",
        details: "التفاصيل",
        communicationWay: "طريقة التواصل",
        authority: "الصلاحية",
        priority: "الأولوية",
        dates: "التواريخ",
        createdAt: "تاريخ الإنشاء",
        timeline: "السجل الزمني",
        // Activities
        allUsers: "كل المستخدمين",
        today: "اليوم",
        yesterday: "الأمس",
        last7Days: "آخر 7 أيام",
        thisMonth: "هذا الشهر",
        allLeadsType: "كل أنواع العملاء",
        freshLead: "عميل جديد",
        coldLead: "عميل بارد",
        call: "مكالمة",
        meeting: "اجتماع",
        whatsapp: "واتساب",
        note: "ملاحظة",
        lead: "العميل",
        type: "النوع",
        date: "التاريخ",
        noActivitiesFound: "لم يتم العثور على أنشطة للمرشحات المحددة.",
        // Properties
        createNew: "إنشاء جديد",
        addDeveloper: "إضافة مطور",
        addProject: "إضافة مشروع",
        addUnit: "إضافة وحدة",
        // Services
        services: "الخدمات",
        servicePackages: "باقات الخدمات",
        serviceProviders: "مقدمي الخدمات",
        duration: "المدة",
        rating: "التقييم",
        // Products
        products: "المنتجات",
        productCategories: "فئات المنتجات",
        suppliers: "الموردون",
        cost: "التكلفة",
        stock: "المخزون",
        sku: "رمز المنتج",
        contactPerson: "الشخص المسؤول",
        specialization: "التخصص",
        realEstateOnly: "هذه الصفحة متاحة فقط لشركات العقارات.",
        servicesOnly: "هذه الصفحة متاحة فقط لشركات الخدمات.",
        productsOnly: "هذه الصفحة متاحة فقط لشركات المنتجات.",
        active: "نشط",
        inactive: "غير نشط",
        units: "الوحدات",
        projects: "المشاريع",
        developers: "المطورون",
        searchUnits: "بحث في الوحدات",
        noUnitsFound: "لم يتم العثور على وحدات.",
        logo: "الشعار",
        developer: "المطور",
        city: "المدينة",
        paymentMethod: "طريقة الدفع",
        update: "تحديث",
        delete: "حذف",
        bedrooms: "غرف النوم",
        // FIX: Added missing translation key.
        bathrooms: "الحمامات",
        price: "السعر",
        // Owners
        addOwner: "إضافة مالك",
        district: "الحي",
        // FIX: Added missing translation key.
        zone: "المنطقة",
        noOwnersFound: "لم يتم العثور على ملاك.",
        // Deals
        searchDeals: "بحث في الصفقات",
        createDeal: "إنشاء صفقة",
        dealId: "المعرف",
        value: "القيمة",
        // Create Deal
        createNewDeal: "إنشاء صفقة جديدة",
        dealInformation: "معلومات الصفقة",
        project: "المشروع",
        startedBy: "بدأت بواسطة",
        closedBy: "أغلقت بواسطة",
        startDate: "تاريخ البدء",
        closedDate: "تاريخ الإغلاق",
        discountPercentage: "نسبة الخصم",
        discountAmount: "مبلغ الخصم",
        totalValue: "القيمة الإجمالية",
        salesCommissionPercentage: "نسبة عمولة المبيعات",
        salesCommissionAmount: "مبلغ عمولة المبيعات",
        description: "الوصف",
        unknownClient: "عميل غير معروف",
        eg1000000: "مثال: 1000000",
        eg10: "مثال: 10",
        calculated: "محسوب تلقائياً",
        eg25: "مثال: 2.5",
        enterNotesAboutDeal: "أدخل أي ملاحظات حول الصفقة...",
        // Users
        autoAssignment: "الإسناد التلقائي",
        on: "مفعل",
        off: "معطل",
        viewUser: "عرض المستخدم",
        createUser: "إنشاء مستخدم",
        editUser: "تعديل المستخدم",
        deleteUser: "حذف المستخدم",
        salesAssistant: "مساعد مبيعات",
        owner: "المالك",
        noPhoneNumber: "لا يوجد رقم هاتف متاح",
        nameRequired: "الاسم مطلوب",
        usernameRequired: "اسم المستخدم مطلوب",
        emailRequired: "البريد الإلكتروني مطلوب",
        passwordRequired: "كلمة المرور مطلوبة",
        phoneRequired: "رقم الهاتف مطلوب",
        enterPhone: "أدخل رقم الهاتف",
        invalidPhone: "صيغة رقم الهاتف غير صحيحة",
        roleRequired: "الدور مطلوب",
        invalidEmail: "صيغة البريد الإلكتروني غير صحيحة",
        passwordMinLength: "كلمة المرور يجب أن تكون 6 أحرف على الأقل",
        // Campaigns
        addCampaign: "إضافة حملة",
        isActive: "نشطة",
        yes: "نعم",
        no: "لا",
        noResultsFound: "لم يتم العثور على نتائج.",
        // Todos
        addTodo: "إضافة مهمة",
        thisWeek: "هذا الأسبوع",
        noTasksForDate: "لا توجد مهام بتاريخ",
        failedToCompleteTodo: "فشل إكمال المهمة. يرجى المحاولة مرة أخرى.",
        completed: "مكتمل",
        // Reports
        allTeams: "كل الفرق",
        selectFiltersPrompt: "اختر مرشحات لعرض التقرير.",
        totalCalls: "إجمالي المكالمات",
        answered: "تم الرد عليها",
        notAnswered: "لم يتم الرد عليها",
        // Integrations
        integration: "التكامل",
        addNewAccount: "إضافة حساب جديد",
        disconnect: "قطع الاتصال",
        noAccountsConnected: "لا توجد حسابات متصلة",
        connectAccountPrompt: "انقر فوق 'إضافة حساب جديد' لتوصيل صفحتك والبدء في التقاط العملاء المحتملين.",
        // General
        status: "الحالة",
        code: "الرمز",
        budget: "الميزانية",
        role: "الدور",
        email: "البريد الإلكتروني",
        unit: "الوحدة",
        // Settings
        leadAssignmentSettings: "إعدادات إسناد العملاء",
        autoRotation: "تمكين التدوير التلقائي للعملاء المتأخرين",
        autoRotationDesc: "عند التمكين، يقوم النظام تلقائيًا بإعادة تعيين العملاء الذين لم تتم متابعتهم خلال وقت محدد.",
        reminderDelayTime: "وقت تأخير التذكير (بالدقائق)",
        reminderDelayTimeDesc: "يحدد هذا الوقت مدة الانتظار قبل تمييز العميل بأنه 'متأخر'.",
        saveSettings: "حفظ الإعدادات",
        channelAutomation: "أتمتة القنوات",
        multiChannelTracking: "تمكين تتبع العملاء متعددي القنوات",
        defaultChannel: "القناة الافتراضية",
        defaultChannelDesc: "تعيين قناة لأي عملاء جدد بمصدر غير معروف.",
        activeChannels: "القنوات النشطة",
        addChannel: "إضافة قناة",
        channel: "القناة",
        addType: "إضافة نوع",
        typeName: "اسم النوع",
        enterTypeName: "أدخل اسم النوع",
        stageAutomation: "أتمتة المراحل",
        autoStageAdvancement: "تمكين التقدم التلقائي للمرحلة",
        requireStageCompletion: "طلب إكمال المرحلة",
        leadStages: "مراحل العملاء",
        addStage: "إضافة مرحلة",
        stageName: "اسم المرحلة",
        required: "مطلوب",
        autoAdvance: "تقدم تلقائي",
        statusConfiguration: "تكوين الحالة",
        enableCustomStatuses: "تمكين الحالات المخصصة",
        requireStatusUpdates: "طلب تحديثات الحالة",
        defaultActiveStatus: "الحالة النشطة الافتراضية",
        defaultActiveStatusDesc: "تعيين الحالة الافتراضية لجميع العملاء الجدد.",
        availableStatuses: "الحالات المتاحة",
        addStatus: "إضافة حالة",
        category: "الفئة",
        followUp: "متابعة",
        closed: "مغلق",
        // Modals & Drawers general
        submit: "إرسال",
        cancel: "إلغاء",
        reset: "إعادة تعيين",
        applyFilters: "تطبيق الفلاتر",
        edit: "تعديل",
        confirmDelete: "هل أنت متأكد أنك تريد حذف هذا العنصر؟ لا يمكن التراجع عن هذا الإجراء.",
        // AddLeadModal
        addNewLead: "إضافة عميل جديد",
        clientName: "اسم العميل",
        enterClientName: "أدخل اسم العميل",
        // FIX: Added missing translation key.
        enterBudget: "أدخل الميزانية",
        phoneNumber1: "رقم الهاتف 1",
        enterPhoneNumber: "أدخل رقم الهاتف",
        assignedTo: "مسند إلى",
        decisionMaker: "صاحب القرار",
        influencer: "مؤثر",
        fresh: "جديد",
        cold: "بارد",
        high: "مرتفع",
        medium: "متوسط",
        low: "منخفض",
        egFacebookAd: "مثال: إعلان فيسبوك",
        // AddActionModal
        for: "لـ",
        stage: "المرحلة",
        untouched: "لم يلمس",
        touched: "تم اللمس",
        following: "متابعة",
        noAnswer: "لا يوجد رد",
        outOfService: "خارج الخدمة",
        // Task Stages
        hold: "انتظار",
        doneMeeting: "تم الاجتماع",
        followAfterMeeting: "متابعة بعد الاجتماع",
        rescheduleMeeting: "إعادة جدولة الاجتماع",
        cancellation: "إلغاء",
        notInterested: "غير مهتم",
        whatsappPending: "واتساب معلق",
        broker: "وسيط",
        resale: "إعادة بيع",
        // AddTodoModal
        deal: "الصفقة",
        selectDeal: "اختر الصفقة",
        reminderDateAndTime: "تاريخ ووقت التذكير",
        enterNotes: "أدخل الملاحظات...",
        loading: "جاري التحميل...",
        pleaseFillRequiredFields: "الرجاء ملء الحقول المطلوبة",
        failedToCreateTodo: "فشل إنشاء المهمة. يرجى المحاولة مرة أخرى.",
        writeActionDetails: "اكتب تفاصيل الإجراء (مثل ملخص المكالمة)",
        reminderDate: "تاريخ التذكير",
        stageUpdated: "تم تحديث المرحلة",
        // AssignLeadModal
        leadsCount: "عدد العملاء",
        selectEmployee: "اختر موظف",
        // FilterDrawer
        filterLeads: "تصفية العملاء",
        teamLeader: "قائد الفريق",
        selectLeader: "اختر قائد",
        assigned: "مسند",
        selectAssignedOrNot: "اختر مسند أم لا",
        unassigned: "غير مسند",
        selectUser: "اختر مستخدم",
        selectLead: "اختر العميل",
        selectAuthority: "اختر الصلاحية",
        leadInfo: "معلومات العميل",
        selectProject: "اختر مشروع",
        selectCampaign: "اختر حملة",
        selectChannel: "اختر قناة",
        qualified: "مؤهل",
        unqualified: "غير مؤهل",
        cancelReasons: "أسباب الإلغاء",
        selectCancelReason: "اختر سبب الإلغاء",
        budgetTooHigh: "الميزانية مرتفعة جدا",
        currentStage: "المرحلة الحالية",
        selectStage: "اختر مرحلة",
        hasStages: "لديه مراحل",
        selectStages: "اختر مراحل",
        selectPriority: "اختر الأولوية",
        excelFilenames: "أسماء ملفات إكسل",
        selectExcel: "اختر ملف إكسل",
        budgetRangeStart: "بداية نطاق الميزانية",
        eg500000: "مثال: 500000",
        budgetRangeEnd: "نهاية نطاق الميزانية",
        delay: "تأخير",
        delayedReminderLeads: "عملاء بتذكير متأخر",
        selectDelayedOrNot: "اختر متأخر أم لا",
        delayed: "متأخر",
        notDelayed: "غير متأخر",
        dateAddedRange: "نطاق تاريخ الإضافة",
        dateAssignedRange: "نطاق تاريخ الإسناد",
        lastActionRange: "نطاق آخر إجراء",
        reminderDateRange: "نطاق تاريخ التذكير",
        // UnitsFilterDrawer
        filterUnits: "تصفية الوحدات",
        filters: "الفلاتر",
        selectBedrooms: "اختر عدد غرف النوم",
        selectBathrooms: "اختر عدد الحمامات",
        selectType: "اختر النوع",
        apartment: "شقة",
        villa: "فيلا",
        finishingType: "نوع التشطيب",
        selectFinishing: "اختر التشطيب",
        finished: "مشطب",
        semiFinished: "نصف تشطيب",
        selectCity: "اختر المدينة",
        selectDistrict: "اختر الحي",
        selectZone: "اختر المنطقة",
        eg2000000: "مثال: 2000000",
        sold: "مباع",
        // AddDeveloperModal
        addNewDeveloper: "إضافة مطور جديد",
        developerName: "اسم المطور",
        enterDeveloperName: "أدخل اسم المطور",
        enterCode: "أدخل الرمز",
        // AddProjectModal
        addNewProject: "إضافة مشروع جديد",
        projectName: "اسم المشروع",
        enterProjectName: "أدخل اسم المشروع",
        // AddUnitModal
        addNewUnit: "إضافة وحدة جديدة",
        unitCode: "رمز الوحدة",
        enterUnitCode: "أدخل رمز الوحدة",
        // AddOwnerModal
        addNewOwner: "إضافة مالك جديد",
        ownerName: "اسم المالك",
        enterOwnerFullName: "أدخل اسم المالك الكامل",
        ownerCode: "رمز المالك",
        enterUniqueCode: "أدخل رمزًا فريدًا",
        ownerPhone: "هاتف المالك",
        enterContactPhoneNumber: "أدخل رقم هاتف الاتصال",
        selectCityPlaceholder: "اختر مدينة...",
        riyadh: "الرياض",
        jeddah: "جدة",
        dammam: "الدمام",
        ownerDistrict: "حي المالك",
        enterSpecificDistrict: "أدخل الحي المحدد",
        // DealsFilterDrawer
        filterDeals: "تصفية الصفقات",
        addedBy: "أضيف بواسطة",
        dealInfo: "معلومات الصفقة",
        selectStatus: "اختر الحالة",
        reservation: "حجز",
        contracted: "تم التعاقد",
        // closed: "مغلق", // This key already exists
        selectMethod: "اختر الطريقة",
        cash: "نقدي",
        installment: "تقسيط",
        selectUnit: "اختر وحدة",
        leadChannel: "قناة العميل",
        google: "جوجل",
        leadCampaign: "حملة العميل",
        datesAndDuration: "التواريخ والمدة",
        leadCreatedAtRange: "نطاق تاريخ إنشاء العميل",
        dealCreatedAtRange: "نطاق تاريخ إنشاء الصفقة",
        durationDays: "المدة (أيام)",
        eg30: "مثال: 30",
        // EditUserModal
        newUserPassword: "كلمة المرور الجديدة",
        leaveBlankPassword: "اتركها فارغة للحفاظ على كلمة المرور الحالية",
        salesManager: "مدير مبيعات",
        salesAgent: "مندوب مبيعات",
        saveChanges: "حفظ التغييرات",
        // DeleteUserModal
        confirmDeleteUser1: "هل أنت متأكد أنك تريد حذف المستخدم",
        confirmDeleteUser2: "؟ لا يمكن التراجع عن هذا الإجراء.",
        errorUpdatingUser: "فشل تحديث المستخدم. يرجى المحاولة مرة أخرى.",
        // AddCampaignModal
        addNewCampaign: "إضافة حملة جديدة",
        enterCampaignName: "أدخل اسم الحملة",
        enterCampaignCode: "أدخل رمز الحملة",
        enterCampaignBudget: "أدخل ميزانية الحملة",
        // AddIntegrationAccountModal
        addNew: "Add New",
        account: "حساب",
        accountName: "اسم الحساب",
        enterAccountName: "أدخل اسم الحساب",
        accountLink: "رابط الحساب",
        egSalesWhatsapp: "مثال: واتساب المبيعات",
        phoneNumber: "رقم الهاتف",
        enterWhatsappNumber: "أدخل رقم الواتساب",
        connected: "متصل",
        disconnected: "غير متصل",
        // ChangePasswordModal
        changePassword: "تغيير كلمة المرور",
        currentPassword: "كلمة المرور الحالية",
        enterCurrentPassword: "أدخل كلمة المرور الحالية",
        newPassword: "كلمة المرور الجديدة",
        enterNewPassword: "أدخل كلمة المرور الجديدة",
        confirmNewPassword: "تأكيد كلمة المرور الجديدة",
        enterConfirmNewPassword: "أدخل كلمة المرور الجديدة مرة أخرى",
        currentPasswordRequired: "كلمة المرور الحالية مطلوبة",
        newPasswordRequired: "كلمة المرور الجديدة مطلوبة",
        confirmPasswordRequired: "تأكيد كلمة المرور مطلوب",
        passwordsDoNotMatch: "كلمات المرور غير متطابقة",
        newPasswordMustBeDifferent: "يجب أن تكون كلمة المرور الجديدة مختلفة عن الحالية",
        passwordChangedSuccessfully: "تم تغيير كلمة المرور بنجاح!",
        errorChangingPassword: "خطأ في تغيير كلمة المرور",
        changing: "جاري التغيير...",
        // Profile
        profile: "الملف الشخصي",
        profileSettings: "إعدادات الملف الشخصي",
        siteCustomization: "تخصيص الموقع",
        primaryColor: "اللون الأساسي",
        activeSubPageColor: "لون الصفحة الفرعية النشط",
        siteLogo: "شعار الموقع",
        profilePicture: "صورة الملف الشخصي",
        upload: "رفع",
        security: "الأمان",
        saveProfile: "حفظ الملف الشخصي",
        // Delete modals
        deleteChannel: "حذف القناة",
        confirmDeleteChannel: "هل أنت متأكد أنك تريد حذف",
        deleteStage: "حذف المرحلة",
        confirmDeleteStage: "هل أنت متأكد أنك تريد حذف",
        deleteStatus: "حذف الحالة",
        confirmDeleteStatus: "هل أنت متأكد أنك تريد حذف",
        cannotDeleteDefault: "لا يمكن حذف الحالة الافتراضية",
        // Registration
        register: "التسجيل",
        dontHaveAccount: "ليس لديك حساب؟",
        alreadyHaveAccount: "هل لديك حساب بالفعل؟",
        createAccount: "إنشاء حسابك",
        registerDescription: "ابدأ إدارة عملك مع نظام CRM القوي لدينا. ابدأ في دقائق.",
        createCompanyAccount: "إنشاء حساب شركتك",
        companyInformation: "معلومات الشركة",
        companyName: "اسم الشركة",
        enterCompanyName: "أدخل اسم الشركة",
        companyNameRequired: "اسم الشركة مطلوب",
        companyDomain: "نطاق الشركة",
        enterCompanyDomain: "مثال: example.com",
        companyDomainRequired: "نطاق الشركة مطلوب",
        invalidDomain: "صيغة النطاق غير صحيحة",
        domainHint: "سيتم استخدامه كمعرف للشركة",
        realEstate: "العقارات",
        ownerInformation: "معلومات المالك",
        firstName: "الاسم الأول",
        enterFirstName: "أدخل الاسم الأول",
        firstNameRequired: "الاسم الأول مطلوب",
        lastName: "اسم العائلة",
        enterLastName: "أدخل اسم العائلة",
        lastNameRequired: "اسم العائلة مطلوب",
        enterEmail: "أدخل عنوان البريد الإلكتروني",
        enterUsername: "أدخل اسم المستخدم",
        usernameMinLength: "يجب أن يكون اسم المستخدم 3 أحرف على الأقل",
        enterPassword: "أدخل كلمة المرور",
        confirmPassword: "تأكيد كلمة المرور",
        selectPlan: "اختر خطة",
        planSelectionHint: "يمكنك البدء بفترة تجريبية مجانية واختيار خطة لاحقاً",
        freeTrial: "فترة تجريبية مجانية",
        trialDescription: "14 يوم تجريبي مجاني، لا حاجة لبطاقة ائتمان",
        free: "مجاني",
        plansWillBeAdded: "ستكون الخطط متاحة بعد التسجيل",
        back: "رجوع",
        next: "التالي",
        registrationFailed: "فشل التسجيل. يرجى المحاولة مرة أخرى.",
        networkError: "خطأ في الشبكة: تعذر الاتصال بالخادم. يرجى التحقق من اتصال الإنترنت والتأكد من أن خادم API متاح.",
    }
};